### PR TITLE
add dockerfile for running in docker-based container environments

### PR DESCRIPTION
**Pull request by MoralCode**

### CODE REVIEW

**Comment by mhum** [comment]
This is a neat idea! However, this also didn't work for me. The script fails with this error:
```sh
~ # ./dns.tcl 
can't find package json
    while executing
"package require json"
    (file "./packages/http.tcl" line 4)
    invoked from within
"source ./packages/http.tcl"
    ("package ifneeded nfsHttp 1.0" script)
    invoked from within
"package require nfsHttp"
    (file "./dns.tcl" line 5)
```

I think the image will also need `tcllib` and `tcl-tls` installed as well. I found a couple of Alpine images that appear to set up the extra stuff this script requires
- https://hub.docker.com/r/efrecon/mini-tcl
- https://hub.docker.com/r/datacore/alpine-tcl

**Comment by MoralCode** [comment]
just added this in based on some of the code in the dockerfiles for that datacore image you linked. thanks!

I haven't tested this beyond just verifying the docker image builds

**Comment by MoralCode** [comment]
ok, this seems to work now and ive deployed it on two different machines so im pretty confident that it works

**Comment by mhum** [comment]
I gave it a test and it works for me, too. Thanks so much for all the work on this!

**Pull request merged**
