### PR TITLE
support IPv6

### PR DESCRIPTION
**Pull request by MoralCode**
i got distracted and wanted to add IPv6 support so i could play around with my ipv6 setup

this builds on top of #16 (so merge that first) but should otherwise be an easy merge

### CODE REVIEW

**Comment by mhum** [comment]
Can you update the branch in your fork? I think that's what's needed for this PR to reflect only the IPv6 updates. I haven't encountered this situation of stacking PRs in a fork before.

Overall the logic looks good! I think there is a leftover comment from setting up args parser. I promise I won't take as long to review this one as your previous PR.

**Comment by MoralCode** [comment]
oh you already merged the other PR - yeah I can rebase this onto that one!

**Review by mhum — APPROVED** [review]
Looks good! Thanks! 

I don't currently have IPV6, so I can't test this. I'll assume it works!

**Comment by MoralCode** [comment]
i made a dummy subdomain on my domain (which is why theres also the "create if not exists" options i added)  and tested it on my laptop so it seems to work - it reuses a lot of the existing functions where possible so it should work just as well as v4

**Comment by mhum** [comment]
Sounds good. Thanks for testing!

**Pull request merged**
